name: Move issues into Todo

on:
  issues:
    types: [opened, unassigned, reopened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: seanhagstrom/github-project-automation-plus@main
        with:
          project: test
          column: Todo
          repo-token: ${{ secrets.GH_TOKEN }}
